# Generated by Django 5.0.8 on 2024-08-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_article_name_articleinfo_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='main/files/images'),
        ),
    ]
