# Generated by Django 5.0.8 on 2024-08-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_articleinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='image',
            field=models.ImageField(upload_to='main/files/images'),
        ),
    ]
