# Generated by Django 5.0.8 on 2024-08-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_articleinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='isactive',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='image',
            field=models.ImageField(upload_to='files/images'),
        ),
    ]
